language: c

env:
  - GHC_VERSION=7.8.3 CABAL_INSTALL_VERSION=1.22

before_install:
  # Install the GHC we want from hvr's PPA
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-$CABAL_INSTALL_VERSION ghc-$GHC_VERSION happy
  - export PATH=/opt/ghc/$GHC_VERSION/bin:/opt/cabal/$CABAL_INSTALL_VERSION/bin:$PATH

install:
  # Fetch the latest package list from hackage
  - travis_retry cabal update

  # Install the Cabal library which matches what cabal-install was built against
  - export CABAL_VERSION=$(cabal --version | sed -n '/using version /s/^[^0-9]*\([0-9\.]*\).*$/\1/p')
  - cabal install Cabal-$CABAL_VERSION

  # Check the versions of everything installed
  - cabal --version
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - ghc-pkg list

  # Install dependencies and build the project
  - ./cabal build

script:
  # Run all the tests
  - ./cabal testci
