[boris]
  version = 1

[build.all-submodules]
  command = [["dangling-refs"]]
[build.all-rebased]
  command = [["rebased"]]
[build.dist-validate]
  command = [["validate-respect"]]

[build.dist-7-10-compiler]
  command = [["master", "build", "dist-7-10", "-C", "icicle-compiler"]]
[build.dist-7-10-core]
  command = [["master", "build", "dist-7-10", "-C", "icicle-core"]]
[build.dist-7-10-data]
  command = [["master", "build", "dist-7-10", "-C", "icicle-data"]]
[build.dist-7-10-source]
  command = [["master", "build", "dist-7-10", "-C", "icicle-source"]]

[build.dist-8-0-compiler]
  command = [["master", "build", "dist-8-0", "-C", "icicle-compiler"]]
[build.dist-8-0-core]
  command = [["master", "build", "dist-8-0", "-C", "icicle-core"]]
[build.dist-8-0-data]
  command = [["master", "build", "dist-8-0", "-C", "icicle-data"]]
[build.dist-8-0-source]
  command = [["master", "build", "dist-8-0", "-C", "icicle-source"]]

[build.branches-7-10-compiler]
  command = [["master", "build", "branches-7-10", "-C", "icicle-compiler"]]
[build.branches-7-10-compiler-runtime]
  command = [["master", "build", "branches-7-10-runtime", "-C", "icicle-compiler"]]
[build.branches-7-10-compiler-sundry]
  command = [["master", "build", "branches-7-10-sundry", "-C", "icicle-compiler"]]
[build.branches-7-10-core]
  command = [["master", "build", "branches-7-10", "-C", "icicle-core"]]
[build.branches-7-10-data]
  command = [["master", "build", "branches-7-10", "-C", "icicle-data"]]
[build.branches-7-10-source]
  command = [["master", "build", "branches-7-10", "-C", "icicle-source"]]

[build.branches-8-0-compiler]
  command = [["master", "build", "branches-8-0", "-C", "icicle-compiler"]]
[build.branches-8-0-compiler-runtime]
  command = [["master", "build", "branches-8-0-runtime", "-C", "icicle-compiler"]]
[build.branches-8-0-compiler-sundry]
  command = [["master", "build", "branches-8-0-sundry", "-C", "icicle-compiler"]]
[build.branches-8-0-core]
  command = [["master", "build", "branches-8-0", "-C", "icicle-core"]]
[build.branches-8-0-data]
  command = [["master", "build", "branches-8-0", "-C", "icicle-data"]]
[build.branches-8-0-source]
  command = [["master", "build", "branches-8-0", "-C", "icicle-source"]]
