[boris]
  version = 1

[build.all-submodules]
  command = [["dangling-refs"]]
[build.all-rebased]
  command = [["rebased"]]
[build.dist-validate]
  command = [["validate-respect"]]

[build.dist-7-10-compiler]
  command = [["master", "build", "dist-7-10", "-C", "icicle-compiler"]]
[build.dist-7-10-core]
  command = [["master", "build", "dist-7-10", "-C", "icicle-core"]]
[build.dist-7-10-data]
  command = [["master", "build", "dist-7-10", "-C", "icicle-data"]]
[build.dist-7-10-source]
  command = [["master", "build", "dist-7-10", "-C", "icicle-source"]]

[build.dist-8-0-compiler]
  command = [["master", "build", "dist-8-0", "-C", "icicle-compiler"]]
[build.dist-8-0-core]
  command = [["master", "build", "dist-8-0", "-C", "icicle-core"]]
[build.dist-8-0-data]
  command = [["master", "build", "dist-8-0", "-C", "icicle-data"]]
[build.dist-8-0-source]
  command = [["master", "build", "dist-8-0", "-C", "icicle-source"]]

[build.branches-7-10-compiler]
  command = [["master", "build", "branches-7-10", "-C", "icicle-compiler"]]
[build.branches-7-10-compiler-psv-struct]
  command = [["master", "build", "branches-7-10-psv-struct", "-C", "icicle-compiler"]]
[build.branches-7-10-compiler-psv-corpus]
  command = [["master", "build", "branches-7-10-psv-corpus", "-C", "icicle-compiler"]]
[build.branches-7-10-compiler-psv-success]
  command = [["master", "build", "branches-7-10-psv-success", "-C", "icicle-compiler"]]
[build.branches-7-10-compiler-psv-failure]
  command = [["master", "build", "branches-7-10-psv-failure", "-C", "icicle-compiler"]]
[build.branches-7-10-compiler-sea]
  command = [["master", "build", "branches-7-10-sea", "-C", "icicle-compiler"]]
[build.branches-7-10-compiler-sundry]
  command = [["master", "build", "branches-7-10-sundry", "-C", "icicle-compiler"]]
[build.branches-7-10-core]
  command = [["master", "build", "branches-7-10", "-C", "icicle-core"]]
[build.branches-7-10-data]
  command = [["master", "build", "branches-7-10", "-C", "icicle-data"]]
[build.branches-7-10-source]
  command = [["master", "build", "branches-7-10", "-C", "icicle-source"]]

[build.branches-8-0-compiler]
  command = [["master", "build", "branches-8-0", "-C", "icicle-compiler"]]
[build.branches-8-0-compiler-psv-struct]
  command = [["master", "build", "branches-8-0-psv-struct", "-C", "icicle-compiler"]]
[build.branches-8-0-compiler-psv-corpus]
  command = [["master", "build", "branches-8-0-psv-corpus", "-C", "icicle-compiler"]]
[build.branches-8-0-compiler-psv-success]
  command = [["master", "build", "branches-8-0-psv-success", "-C", "icicle-compiler"]]
[build.branches-8-0-compiler-psv-failure]
  command = [["master", "build", "branches-8-0-psv-failure", "-C", "icicle-compiler"]]
[build.branches-8-0-compiler-sea]
  command = [["master", "build", "branches-8-0-sea", "-C", "icicle-compiler"]]
[build.branches-8-0-compiler-sundry]
  command = [["master", "build", "branches-8-0-sundry", "-C", "icicle-compiler"]]
[build.branches-8-0-core]
  command = [["master", "build", "branches-8-0", "-C", "icicle-core"]]
[build.branches-8-0-data]
  command = [["master", "build", "branches-8-0", "-C", "icicle-data"]]
[build.branches-8-0-source]
  command = [["master", "build", "branches-8-0", "-C", "icicle-source"]]
