[master]
  runner = "s3://ambiata-dist/master-ambiata/master-haskell-library-0.0.1-20151209065455-431f7fe"
  version = 1
  sha1 = "5a89a62ecfc4b66300436840c53c7f643ffec707"

[build.dist]
  HADDOCK="true"

[build.dist-bench]
  TEST="false"
  BENCH="true"
  PUBLISH_BENCH="icicle"  

[build.branches]

[build.branches-bench]
  TEST="false"
  BENCH="true"
