[master]
  runner = "s3://ambiata-dispensary-v2/dist/master/master-haskell/linux/x86_64/20170724213527-c4b2de4/master-haskell-20170724213527-c4b2de4"
  version = 1
  sha1 = "09aa2a97367596116e8d12112bf68464919d4815"

[global]
  CACHE = "true"
  ICICLE_CC_OPTIONS = "-Wall -Werror"

[build.dist-7-10]
  GHC_VERSION="7.10.2"
  CABAL_VERSION="1.24.0.0"
  PUBLISH = "true"
  PUBLISH_S3 = "$AMBIATA_ARTEFACTS_MASTER"
  PUBLISH_EXECUTABLES = "icicle"

[build.dist-8-0]
  GHC_VERSION = "8.0.1"
  CABAL_VERSION = "1.24.0.0"

[build.branches-7-10]
  TEST = "false"
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.24.0.0"
  PUBLISH = "true"
  PUBLISH_S3 = "$AMBIATA_ARTEFACTS_BRANCHES"
  PUBLISH_EXECUTABLES = "icicle"

[build.branches-7-10-runtime]
  TEST_SUITE = "runtime"
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.24.0.0"

[build.branches-7-10-sundry]
  TEST_SUITE = "sundry"
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.24.0.0"

[build.branches-8-0]
  TEST = "false"
  GHC_VERSION = "8.0.1"
  CABAL_VERSION = "1.24.0.0"

[build.branches-8-0-runtime]
  TEST_SUITE = "runtime"
  GHC_VERSION = "8.0.1"
  CABAL_VERSION = "1.24.0.0"

[build.branches-8-0-sundry]
  TEST_SUITE = "sundry"
  GHC_VERSION = "8.0.1"
  CABAL_VERSION = "1.24.0.0"
